image:
    gradle:8.5-jdk21

stages:
  - build

build:
    stage: build
    script:
        - gradle clean build
    only:
      changes:
        - src/**/*
        - build.gradle.kts
        - settings.gradle.kts
    artifacts:
        paths:
        - build/libs/*.jar
        expire_in: 2 weeks
