#
# Uriel Habbo Server
# - Hotel settings / mechanics
#

[hotel]
defaultRoomId = 0 # 0 = no room, hotelview

[habboClub]
discountEnabled = false
discountDaysBeforeEnd = 7

[habbos]


[habbos.wardrobe]
figureDataUrl = "https://habbo.com/gamedata/figuredata/0"
validateLooksOnHabboClubExpire = true
validateLooksOnLogin = true
validateLooksOnChange = true

[habbos.inventory]
storeItemDataOnPickUp = false

[habbos.subscription]
deleteExpiredSubscriptions = true
