#
# Uriel Habbo Server
# - Hotel settings / mechanics
#

[hotel]
defaultRoomId = 0 # 0 = no room, hotelview

[habboClub]
discountEnabled = false
discountDaysBeforeEnd = 7

[habbos]
defaultChatBubbleId = 1
alertChatBubbleId = 2

[habbos.rooms]
maxRoomsWithHabboClub = 35
maxRooms = 25

[habbos.wardrobe]
figureDataUrl = "https://habbo.com/gamedata/figuredata/0"
validateLooksOnHabboClubExpire = true
validateLooksOnLogin = true
validateLooksOnChange = true
validateLooksOnSave = true

[habbos.inventory]
storeFurniDataOnPickUp = false

[habbos.subscription]
deleteExpiredSubscriptions = true

[rooms]
noDelayOnWalk = true

[commands]
prefix = ":"
