#
# Uriel Habbo Server
# - Server configuration
#

[server]
ip = "127.0.0.1"
port = 2096
route = "/"

[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = ""
databaseName = "habbo"

[connections]
maxConnectedClients = 1000 # -1 = unlimited
maxConnectionsPerIp = 5 # -1 = unlimited

[packets]
packetRateLimitTime = 1000 # ms
packetRateLimitAmount = 10 # packets, -1 = unlimited

[security]
refreshSSOTicketOnLogin = false

[tickLoops]
hotelTicksPerSecond = 25
roomTicksPerSecond = 25
