#
# Uriel Habbo Server
# - Hotel settings / mechanics
#

[hotel]
defaultRoomId = 0 # 0 = no room, hotelview

[habboClub]
discountEnabled = false
discountDaysBeforeEnd = 7

[habbos]
defaultChatBubbleId = 1
alertChatBubbleId = 2

[habbos.messenger]
maxFriendsWithHabboClub = 500
maxFriends = 200

[habbos.rooms]
maxRoomsWithHabboClub = 35
maxRooms = 25

[habbos.badges]
maxActiveBadges = 5

[habbos.wardrobe]
figureDataUrl = "https://yourhotel.com/gamedata/FigureData.json" # Set your Nitro's FigureData here
maxSlots = 10
validateLooksOnHabboClubExpire = true
validateLooksOnLogin = true
validateLooksOnChange = true
validateLooksOnSave = true

[habbos.inventory]
storeFurniDataOnPickUp = false

[habbos.subscriptions]
deleteExpiredSubscriptions = true

[rooms]
noDelayOnWalk = true

[commands]
prefix = ":"
